from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any

import structlog
from structlog.contextvars import merge_contextvars

from .pii import scrub_text

LOG_PATH = Path(os.getenv("LOG_PATH", "data/logs.jsonl"))


class JsonlFileProcessor:
    def __call__(self, logger: Any, method_name: str, event_dict: dict[str, Any]) -> dict[str, Any]:
        LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        rendered = structlog.processors.JSONRenderer()(logger, method_name, event_dict)
        with LOG_PATH.open("a", encoding="utf-8") as f:
            f.write(rendered + "\n")
        return event_dict



# Join keys and low-cardinality dimensions. They are generated by us, never by the
# caller, so scrubbing them can only corrupt: user_id_hash is 12 hex chars and a hash
# that lands on all digits matches the cccd pattern, which would silently break the
# join between an event and the user it belongs to.
SYSTEM_FIELDS = frozenset(
    {"ts", "level", "service", "env", "correlation_id", "user_id_hash", "model", "error_type"}
)


def scrub_event(_: Any, __: str, event_dict: dict[str, Any]) -> dict[str, Any]:
    def _scrub_recursive(obj: Any) -> Any:
        if isinstance(obj, dict):
            return {k: _scrub_recursive(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [_scrub_recursive(item) for item in obj]
        if isinstance(obj, str):
            return scrub_text(obj)
        return obj

    for key in list(event_dict.keys()):
        if key not in SYSTEM_FIELDS:
            event_dict[key] = _scrub_recursive(event_dict[key])
    return event_dict



def configure_logging() -> None:
    logging.basicConfig(format="%(message)s", level=getattr(logging, os.getenv("LOG_LEVEL", "INFO")))
    structlog.configure(
        processors=[
            merge_contextvars,
            structlog.processors.add_log_level,
            structlog.processors.TimeStamper(fmt="iso", utc=True, key="ts"),
            scrub_event,
            structlog.processors.StackInfoRenderer(),
            structlog.processors.format_exc_info,
            JsonlFileProcessor(),
            structlog.processors.JSONRenderer(),
        ],
        wrapper_class=structlog.make_filtering_bound_logger(logging.INFO),
        cache_logger_on_first_use=True,
    )



def get_logger() -> structlog.typing.FilteringBoundLogger:
    return structlog.get_logger()
